choco install foxitreader -y
choco install anydesk.install -y
choco install googlechrome -y
choco install firefox -y
choco install 7zip.install -y
choco install vlc -y
choco install chocolateygui -y
choco install notepadplusplus.install -y
choco install python -y
choco install microsoft-windows-terminal -y